#!/usr/bin/env node
/* Generate docs/control-library.md from assets/data.js, so the written
   reference cannot drift from the control set the app actually applies.

     node tools/gen-docs.js
*/

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'assets', 'data.js'), 'utf8');

// data.js declares top-level consts and has no imports, so evaluating it in a
// function scope and handing back the bindings is enough.
const { GATES, RISK_QUESTIONS, ESCALATIONS, TIERS, CONTROLS, TIER1_AVG_SEVERITY, TIER3_AVG_SEVERITY, PROHIBITED_CHECKS } =
  new Function(`${src}\nreturn { GATES, RISK_QUESTIONS, ESCALATIONS, TIERS, CONTROLS, TIER1_AVG_SEVERITY, TIER3_AVG_SEVERITY, PROHIBITED_CHECKS };`)();

const L = [];
const p = (...s) => L.push(...s);

p('# Control library',
  '',
  '<!-- Generated by tools/gen-docs.js from assets/data.js. Do not edit by hand. -->',
  '',
  `${CONTROLS.length} controls. Each one is required only when the gate 2 answers make it required —`,
  'the app derives the set from the underlying answers rather than from the tier label alone,',
  'so a lower-risk use case gets a genuinely shorter list rather than the same list with',
  '"not applicable" written next to most of it.',
  '');

p('## Risk tiers', '');
for (const k of Object.keys(TIERS)) {
  p(`**${TIERS[k].name}** — ${TIERS[k].means}`, '');
}
p(`The cutoff itself: the eight gate-2 answers are weighted (see below), then averaged into a`,
  `single severity figure on the same 0-3 scale each question uses. **Tier 1 begins once that`,
  `weighted average reaches ${TIER1_AVG_SEVERITY.toFixed(1)} (High)**; **Tier 3 requires it to stay`,
  `under ${TIER3_AVG_SEVERITY.toFixed(1)} (Moderate)**. Escalation rules (below) can still override`,
  `the result upward regardless of where the average lands — that part of the design is deliberate`,
  `and unaffected by the weighting.`, '');

p('## Article 5 screen (gate 1)', '',
  'Answered before the eight risk questions below, and deliberately not folded into them: a "yes"',
  'here is not a higher tier, it is a stop. These map to EU AI Act Article 5(1)(a)-(h) — practices',
  'that are not permitted to place on the market in the EU at all, subject to narrow statutory',
  'exceptions, regardless of what controls sit around them.', '');
for (const c of PROHIBITED_CHECKS) {
  p(`- **${c.article}** — ${c.q}`);
}
p('');

p('## The eight questions at gate 2', '',
  'Each answer is scored 0-3 (Low-Severe) and multiplied by the question\'s weight before the',
  'eight are averaged into a single severity figure. See `docs/control-library.md`\'s "Risk',
  'tiers" section above for what that average has to reach for each tier.', '');
for (const q of RISK_QUESTIONS) {
  p(`### ${q.label} — weight ${q.weight}`, '', `*Why it is asked:* ${q.why}`, '', `*Why this weight:* ${q.weightWhy}`, '');
  q.options.forEach((o, i) => p(`${i}. ${o}`));
  p('');
}

p('## Escalation rules', '',
  'Combinations that set a tier floor regardless of the arithmetic. This is where',
  'judgement sits: individually moderate answers can combine into something that is not.',
  '');
for (const e of ESCALATIONS) {
  p(`- **Tier ${e.floor} floor** — ${e.say}`);
}
p('');

p('## Controls', '');
const groups = [...new Set(CONTROLS.map(c => c.group))];
for (const g of groups) {
  p(`### ${g}`, '');
  for (const c of CONTROLS.filter(x => x.group === g)) {
    p(`#### ${c.name}`, '',
      c.plain, '',
      `**Ask in the room:** ${c.ask}`, '',
      `**NIST AI RMF:** ${c.nist.join(', ')}`, '',
      `**EU AI Act / other:** ${c.eu.join('; ')}`, '');
  }
}

p('## Gate reference', '',
  '| # | Question asked | Formal name | Time | In the room | Pass rule |',
  '|---|---|---|---|---|---|');
for (const g of GATES) {
  p(`| ${g.n} | ${g.client} | ${g.formal} | ${g.time} | ${g.room.join(', ')} | ${g.passRule} |`);
}
p('');

const out = path.join(root, 'docs', 'control-library.md');
fs.writeFileSync(out, L.join('\n'));
console.log(`wrote ${path.relative(root, out)} — ${CONTROLS.length} controls, ${RISK_QUESTIONS.length} questions, ${ESCALATIONS.length} escalation rules`);
